# app/config/common/config_vich.yml
twig:
    form_themes:
        - 'VichUploaderBundle:Form:fields.html.twig'

vich_uploader:
    db_driver: orm
    mappings:
        concert_poster:
            uri_prefix:         /uploads/concert/poster
            upload_destination: %kernel.root_dir%/../www/uploads/concert/poster
            namer:              vich_uploader.namer_uniqid
            delete_on_remove:   true
            delete_on_update:   true

        article_block_image:
            uri_prefix:         /uploads/article_block/image
            upload_destination: %kernel.root_dir%/../www/uploads/article_block/image
            namer:              vich_uploader.namer_uniqid
            delete_on_remove:   true
            delete_on_update:   true

        musician_photo:
            uri_prefix:         /uploads/musician/photo
            upload_destination: %kernel.root_dir%/../www/uploads/musician/photo
            namer:              vich_uploader.namer_uniqid
            delete_on_remove:   true
            delete_on_update:   true

        biography_photo:
            uri_prefix:         /uploads/biography/photo
            upload_destination: %kernel.root_dir%/../www/uploads/biography/photo
            namer:              vich_uploader.namer_uniqid
            delete_on_remove:   true
            delete_on_update:   true

        album_cover:
            uri_prefix:         /uploads/album/cover
            upload_destination: %kernel.root_dir%/../www/uploads/album/cover
            namer:              vich_uploader.namer_uniqid
            delete_on_remove:   true
            delete_on_update:   true

        album_track:
            uri_prefix:         /uploads/album/track
            upload_destination: %kernel.root_dir%/../www/uploads/album/track
            namer:              vich_uploader.namer_uniqid
            delete_on_remove:   true
            delete_on_update:   true

        photo_album_photo:
            uri_prefix:         /uploads/photo_album/photo
            upload_destination: %kernel.root_dir%/../www/uploads/photo_album/photo
            namer:              vich_uploader.namer_uniqid
            delete_on_remove:   true
            delete_on_update:   true
