# app/config/common/config_liip.yml
liip_imagine:
    resolvers:
       default:
          web_path:
              web_root:     %kernel.root_dir%/../www
              cache_prefix: media/cache

    loaders:
       default:
          filesystem:
             data_root: %kernel.root_dir%/../www/

    filter_sets:
        cache: ~

        affiche_poster_thumb:
            quality: 100
            filters:
                thumbnail: { size: [500, 500], mode: outbound }

        blog_image_thumb:
            quality: 100
            filters:
                thumbnail: { size: [500, 500], mode: outbound }

        blog_article_thumb:
            quality: 100
            filters:
                thumbnail: { size: [1200, 1200], mode: outbound }

        album_cover_thumb:
            quality: 100
            filters:
                thumbnail: { size: [500, 500], mode: outbound }

        musician_photo_thumb:
            quality: 100
            filters:
                thumbnail: { size: [500, 500], mode: outbound }

        photo_album_photo_thumb:
            quality: 100
            filters:
                thumbnail: { size: [500, 500], mode: outbound }

        photo_thumb:
            quality: 100
            filters:
                relative_resize: { widen: 500 }
