# app/config/common/config_vich.yml
twig:
    form_themes:
        - 'VichUploaderBundle:Form:fields.html.twig'

vich_uploader:
    db_driver: orm
    mappings:
        musician_photo:
            uri_prefix:         /uploads/musician/photo
            upload_destination: %kernel.root_dir%/../www/uploads/musician/photo
            namer:              vich_uploader.namer_uniqid
            delete_on_remove:   true
            delete_on_update:   true

        concert_poster:
            uri_prefix:         /uploads/concert/poster
            upload_destination: %kernel.root_dir%/../www/uploads/concert/poster
            namer:              vich_uploader.namer_uniqid
            delete_on_remove:   true
            delete_on_update:   true

        album_cover:
            uri_prefix:         /uploads/album/cover
            upload_destination: %kernel.root_dir%/../www/uploads/album/cover
            namer:              vich_uploader.namer_uniqid
            delete_on_remove:   true
            delete_on_update:   true

        album_track:
            uri_prefix:         /uploads/album/track
            upload_destination: %kernel.root_dir%/../www/uploads/album/track
            namer:              vich_uploader.namer_uniqid
            delete_on_remove:   true
            delete_on_update:   true
