# app/config/common/config_vich.yml
twig:
    form_themes:
        - 'VichUploaderBundle:Form:fields.html.twig'

vich_uploader:
    db_driver: orm
    mappings:
        some_images:
            uri_prefix:         /images/some
            upload_destination: %kernel.root_dir%/../www/images/some
            namer:              vich_uploader.namer_uniqid
            delete_on_remove:   true
            delete_on_update:   true
