# app/config/common/config_sonata_admin.yml
doctrine:
    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        entity_managers:
            default:
                mappings:
                    SonataUserBundle: ~
                    FOSUserBundle: ~
                    ApplicationSonataUserBundle: ~

twig:
    form:
        resources:
            - 'SonataCoreBundle:Form:datepicker.html.twig'

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts: [admin]
        sonata.user.block.menu:
        sonata.user.block.account:
        sonata.block.service.text:

parameters:
    sonata.user.admin.user.class: AppBundle\Admin\UserAdmin

sonata_user:
    manager_type: orm
    class:
        user:  Application\Sonata\UserBundle\Entity\User
        group: Application\Sonata\UserBundle\Entity\Group

fos_user:
    db_driver:     orm
    firewall_name: main
    user_class:    Application\Sonata\UserBundle\Entity\User

    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager

    service:
        user_manager: sonata.user.orm.user_manager

sonata_admin:
    title:      "Управление"
    dashboard:
        blocks:
            -
                position: left
                type:     sonata.admin.block.admin_list
            -
                position: right
                type:     sonata.block.service.text
                settings:
                    content: >
                        <h2>Система управления контентом</h2>
                        <p>
                            На вашем сайте для администрирования доступны следующие разделы:
                            <br><br>
                            <h4>Новости</h4>
                            Афиша концертов и блог группы.
                            <br><br>
                            <h4>Группа</h4>
                            Биографии музыкантов и фотоальбомы.
                            <br><br>
                            <h4>Творчество</h4>
                            Альбомы и песни группы.
                            <br><br>
                            <h4>Тэги</h4>
                            Персональные тэги для контента.
                            <br><br>
                            <h4>Подписчики</h4>
                            Подписчики сайта.
                            <br><br>
                            <h4>SEO (Поисковая оптимизация)</h4>
                            В основном это служебная информация для поисковых роботов.
                            <br><br>
                            <h4>Пользователи</h4>
                            Контроль пользователей системы управления.
                        </p>
    templates:
        layout:     ApplicationSonataUserBundle:Admin:standard_layout.html.twig
        user_block: ApplicationSonataUserBundle:Admin\Core:user_block.html.twig

services:
    sonata.user.admin.group:
        abstract: true
        public:   false

    sonata.admin.concert:
        class: AppBundle\Admin\ConcertAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Новости", label: "Афиша" }
        arguments:
            - ~
            - AppBundle\Entity\Concert
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]

    sonata.admin.article:
        class: AppBundle\Admin\ArticleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Новости", label: "Блог" }
        arguments:
            - ~
            - AppBundle\Entity\Article
            - AppBundle:Admin\ArticleAdmin
        calls:
            - [ setTranslationDomain, [AppBundle] ]

    sonata.admin.article_block:
        class: AppBundle\Admin\ArticleBlockAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "", label: "", show_in_dashboard: false }
        arguments:
            - ~
            - AppBundle\Entity\ArticleBlock
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]

    sonata.admin.musician:
        class: AppBundle\Admin\MusicianAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Группа", label: "Музыканты" }
        arguments:
            - ~
            - AppBundle\Entity\Musician
            - AppBundle:Admin\MusicianAdmin
        calls:
            - [ setTranslationDomain, [AppBundle] ]

    sonata.admin.biography:
        class: AppBundle\Admin\BiographyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "", label: "", show_in_dashboard: false }
        arguments:
            - ~
            - AppBundle\Entity\Biography
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]

    sonata.admin.questionary:
        class: AppBundle\Admin\QuestionaryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "", label: "", show_in_dashboard: false }
        arguments:
            - ~
            - AppBundle\Entity\Questionary
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]

    sonata.admin.photo_album:
        class: AppBundle\Admin\PhotoAlbumAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Группа", label: "Фотоальбомы" }
        arguments:
            - ~
            - AppBundle\Entity\PhotoAlbum
            - AppBundle:Admin\PhotoAlbumAdmin
        calls:
            - [ setTranslationDomain, [AppBundle] ]

    sonata.admin.photo:
        class: AppBundle\Admin\PhotoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "", label: "", show_in_dashboard: false }
        arguments:
            - ~
            - AppBundle\Entity\Photo
            - 'PixSortableBehaviorBundle:SortableAdmin'
        calls:
            - [ setTranslationDomain, [AppBundle] ]
            - [ setPositionService, [ "@pix_sortable_behavior.position" ]]

    sonata.admin.album:
        class: AppBundle\Admin\AlbumAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Творчество", label: "Альбомы" }
        arguments:
            - ~
            - AppBundle\Entity\Album
            - AppBundle:Admin\AlbumAdmin
        calls:
            - [ setTranslationDomain, [AppBundle] ]

    sonata.admin.song:
        class: AppBundle\Admin\SongAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "", label: "", show_in_dashboard: false }
        arguments:
            - ~
            - AppBundle\Entity\Song
            - 'PixSortableBehaviorBundle:SortableAdmin'
        calls:
            - [ setTranslationDomain, [AppBundle] ]
            - [ setPositionService, [ "@pix_sortable_behavior.position" ]]

    sonata.admin.tag:
        class:      AppBundle\Admin\TagAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Тэги", label: "Тэги" }
        arguments:
            - ~
            - AppBundle\Entity\Tag
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]

    sonata.admin.subscriber:
        class: AppBundle\Admin\SubscriberAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Подписчики", label: "Подписчики" }
        arguments:
            - ~
            - AppBundle\Entity\Subscriber
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]

    sonata.admin.metadata:
        class: AppBundle\Admin\MetadataAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "SEO", label: "Метаданные" }
        arguments:
            - ~
            - AppBundle\Entity\Metadata
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
