# app/config/common/config_vich.yml
twig:
    form_themes:
        - 'VichUploaderBundle:Form:fields.html.twig'

vich_uploader:
    db_driver: orm
    mappings:
        musician_photo:
            uri_prefix:         /uploads/musician/photo
            upload_destination: %kernel.root_dir%/../www/uploads/musician/photo
            namer:              vich_uploader.namer_uniqid
            delete_on_remove:   true
            delete_on_update:   true
