# app/config/common/config.yml
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    # Bundles config
    - { resource: config_stof.yml }
    - { resource: config_sonata_admin.yml }
    - { resource: config_a2lix.yml }
    - { resource: config_vich.yml }
    - { resource: config_liip.yml }
    - { resource: config_formatter.yml }
    # Services
    - { resource: services.yml }
    - { resource: @MenuBundle/Menu/config/servicesMenu.yml }

framework:
    translator: { fallbacks: ["%locale%"] }
    secret:     "%secret%"
    router:
        resource: "%kernel.root_dir%/config/common/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    # Twig globals
    globals:
        default_locale: "%locale%"
        developers:     "%developers%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    read_from:      "%kernel.root_dir%/../www"
    write_to:       '%kernel.root_dir%/../www'
    bundles:        [ AppBundle, TwigBundle ]
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true
                dql:
                    string_functions:
                        YEAR: DoctrineExtensions\Query\Mysql\Year

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
