redirect_to_default_locale:
    path: "/{url}"
    host: "{locale}.{domain}"
    defaults:
        _controller: AppBundle:Redirect:redirectToDefaultLocale
    requirements:
        url:    .*
        locale: "%locale%"
        domain: "%domain%"

access_denied:
    path: /403
    defaults :
        _controller: FrameworkBundle:Template:template
        template:    'TwigBundle:Exception:error403.html.twig'

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

sonata_user_profile_show:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix:   /mastermind

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix:   /mastermind

_sonata_admin:
    resource: .
    type:     sonata_admin
    prefix:   /mastermind
    defaults:
        _locale: "%locale%"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
