security:
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
          - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        admin:
            pattern: /mastermind(.*)
            context: user
            form_login:
                provider:     fos_userbundle
                login_path:   /mastermind/login
                use_forward:  false
                check_path:   /mastermind/login_check
                failure_path: null
            logout:
                path: /mastermind/logout
            anonymous: true
            security:  true
            access_denied_url: access_denied

        main:
            pattern: ^/
            form_login:
                provider:      fos_userbundle
                csrf_provider: form.csrf_provider
                check_path:    access_denied
                login_path:    access_denied
            logout:    true
            anonymous: true
            security:  true
            access_denied_url: access_denied

    access_control:
        - { path: ^/403$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/mastermind/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mastermind/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mastermind/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/mastermind/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
