# app/config/common/services.yml
services:
    # Twig

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }

    # Events

    app.page_init_listener:
        class:     AppBundle\EventListener\PageInitListener
        scope:     request
        arguments: [ "@request", "@app.metadata" ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    # Common

    app.metadata:
        class: AppBundle\Service\Metadata
        arguments:
            - "@doctrine.orm.entity_manager"

    app.mailer_shortcut:
        class: AppBundle\Service\MailerShortcut
        arguments:
            - "@mailer"

    # Specific

    app.action_handler:
        class: AppBundle\Service\ActionHandler

    app.subscription:
        class: AppBundle\Service\Subscription
        calls:
            - [setManager, ["@doctrine.orm.entity_manager"]]

    app.subscription_sender:
        class: AppBundle\Service\SubscriptionSender
        arguments:
            - "%emails%"
        calls:
            - [setManager, ["@doctrine.orm.entity_manager"]]
            - [setTranslator, ["@translator"]]
            - [setTemplating, ["@templating"]]
            - [setMailerShortcut, ["@app.mailer_shortcut"]]
