# app/config/common/services.yml
services:
    # Twig

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    twig.extension.routing:
        class:  AppBundle\Twig\AppRoutingExtension
        public: false
        arguments:
            - "@router"
            - "@request_stack"
            - "%locale%"
        tags:
            - { name: twig.extension }

    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }

    # Event listeners

    app.page_init_listener:
        class:     AppBundle\EventListener\PageInitListener
        scope:     request
        arguments: [ "@request", "@app.metadata" ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    app.listener.fallback.browser:
        class: AppBundle\EventListener\Fallback\BrowserFallbackListener
        calls:
            - [setBrowserFallbackController, [ "@app.browser_fallback_controller" ]]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    # Controller

    app.browser_fallback_controller:
        class: AppBundle\Controller\Fallback\BrowserFallbackController
        calls:
            - [setTemplating, [ "@templating" ]]

    # Common

    app.metadata:
        class: AppBundle\Service\Metadata
        arguments:
            - "@doctrine.orm.entity_manager"

    app.mailer_shortcut:
        class: AppBundle\Service\MailerShortcut
        arguments:
            - "@mailer"

    app.views_counter:
        class: AppBundle\Service\ViewsCounter
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@session"

    # Specific

    app.action_handler:
        class: AppBundle\Service\ActionHandler

    app.action_entity_manager:
        class: AppBundle\Service\ActionEntityManager
        calls:
            - [setRequestStack, ["@request_stack"]]
            - [setRouter, ["@router"]]
            - [setTranslator, ["@translator"]]
            - [setTwigEngine, ["@twig"]]
            - [setUploaderHelper, ["@vich_uploader.templating.helper.uploader_helper"]]
            - [setImagineController, ["@liip_imagine.controller"]]

    app.subscription:
        class: AppBundle\Service\Subscription
        calls:
            - [setManager, ["@doctrine.orm.entity_manager"]]

    app.subscription_sender:
        class: AppBundle\Service\SubscriptionSender
        arguments:
            - "%emails%"
        calls:
            - [setManager, ["@doctrine.orm.entity_manager"]]
            - [setTranslator, ["@translator"]]
            - [setTemplating, ["@templating"]]
            - [setMailerShortcut, ["@app.mailer_shortcut"]]
